### ISSUE TITLE
How do I create a Mat from data?

### ISSUE THREAD

**Issue by GRASBOCK** [twistedfall/opencv-rust#114]
I am asking for help (this is not a bug report), so if this is not the right place to ask, be so kind and direct me to a place where I can ask questions specific to this crate.

I have trouble getting the basics. I have used the c++ version plenty, but I can't transfer.
What I want to do is load a custom video format frame by frame into a `Mat`.
That format is nothing more than a block of image sequences, where each image is also just a block of i16 pixels row by row. A `Vec<u8>` buffer is given that contains all the video data.
How do I create a `Mat` by copying a frame slice into its memory. Or can I create a 3 dimensional Mat and extract the 2d Mats frame by frame from it? 
To visualize:
```
// 3 frames, 2x2 images
let buf = vec![255, 255, 255, 255,    0, 0, 0, 0,    127, 127, 127, 127]
//             image 0                image 1        image 2
```

Also, what is the difference between `prelude::Mat` and `core::Mat`?

While the examples sure help a lot, they don't cover the loading from data. 
An example would be great.

**Comment by twistedfall** [comment]
Please check [Mat::from_slice](https://docs.rs/opencv/0.34.0/opencv/core/struct.Mat.html#method.from_slice) method with optionally calling [reshape](https://docs.rs/opencv/0.34.0/opencv/core/prelude/trait.MatTrait.html#method.reshape) after.

If you're looking for maximum performance, then check `new_*_with_data` family of unsafe functions, e.g. [new_rows_cols_with_data](https://docs.rs/opencv/0.34.0/opencv/core/struct.Mat.html#method.new_rows_cols_with_data). But managing the lifetime of the buffer is entirely your responsibility in that case.

> Also, what is the difference between prelude::Mat and core::Mat?

There is no difference, it's just that `Mat` is also imported as part of `use prelude::*` because it's such a commonly used struct.

> While the examples sure help a lot, they don't cover the loading from data.

You should also take a look at the tests, they contain a lot of code samples, e.g.: https://github.com/twistedfall/opencv-rust/blob/master/tests/mat.rs

**Comment by GRASBOCK** [comment]
Uff, that was a lot of figuring out and reading but I think I understand the basics.
The Tests really helped a lot. Thank you very much!

In the end I didn't use a 3 dimensional matrix but a vector that contains Matrices for every frame that each have an offset to the start of the buffer.
