### ISSUE TITLE
Vector::<Vector::<Point2d>>::new()

### ISSUE THREAD

**Issue by ghost** [twistedfall/opencv-rust#138]
why no Vector::<Vector::<Point2d>>::new
need for project

**Comment by twistedfall** [comment]
Generally it’s because no OpenCV function references it directly so it’s not automatically generated. Which OpenCV functions are you trying to call that requires this type?

**Comment by linrium** [comment]
You can use ```let a: Vector<Vector<something>> = Vector::new()```

**Comment by twistedfall** [comment]
Nope, it won't work in this particular case, because there need to be some additional auto-generated definitions specifically for `Vector::<Vector::<Point2d>>` and they are not generated by default because no OpenCV function has this type in its signature. It can be force-generated, but I wonder which function needs this type.

**Comment by twistedfall** [comment]
@lisa-rwito So would you be able to tell which OpenCV function you’re trying to call that needs the `Vector::<Vector::<Point2d>>` type?

**Comment by ghost** [comment]
I want to call FindPoints but code no work nevdur no pvdjload for this fhnction

**Comment by ghost** [comment]
I mean FindContoues

**Comment by twistedfall** [comment]
Well, `find_countours` function needs `Vector::<Vector::<Point>>` argument type for its output argument `contours`. I've tried running it with (locally forcefully generated) `Vector::<Vector::<Point2d>>` and it fails with format mismatch error. So please use `Vector::<Vector::<Point>>` type for that specific function. If you need this type for another function please feel free to reopen this issue!
