### ISSUE TITLE
Where are the implementations of externs functions like`cv_Mat_delete`? How does this library handle `Mat`?

### ISSUE THREAD

**Issue by fzyzcjy** [twistedfall/opencv-rust#268]
Hi thanks for this wonderful binding! When reading source code, I see things like

https://github.com/twistedfall/opencv-rust/blob/master/src/opencv/hub/core.rs#L10285-L10290

However, where is the C side of `cv_Mat_delete`? I cannot find it even with a search in GitHub.

In addition, I wonder how this library handles the memory management of `Mat`? As we know, `Mat` has a reference-counting built inside it, so in C++ we can happily copy Mats around and it is very cheap. However, with this binding and using Rust, can we do this?

Thanks!

**Comment by twistedfall** [comment]
All the bindings are generated on the fly when you build the library, so you can find the actual files in the build directory (when you build with `-vv` you would see the actual dir in the debug output). That includes all supporting `*.cpp` files. That’s where you would find `cv_Mat_delete`.

Moving `Mat` around is easy because we in fact are not moving it around, it’s allocated on the heap and stays there for its lifetime.

**Comment by fzyzcjy** [comment]
@twistedfall Thanks!
