### ISSUE TITLE
Access underlying Mat buffer with mutability?

### ISSUE THREAD

**Issue by fzyzcjy** [twistedfall/opencv-rust#275]
Hi thanks for the lib! I wonder how can I access the underlying byte buffer of Mat with mutability?

Attempt: With `mat.ptr(0)` I can get an immutable reference to the underlying byte buffer at index 0. But I want to get a reference to the whole underlying buffer, and want it to be mutable.

Thanks!

**Comment by twistedfall** [comment]
I've just released v0.55.0 which contains the necessary functionality: just call `Mat::data_bytes_mut()`

**Comment by fzyzcjy** [comment]
Wow you are so quick! Thanks!

**Comment by fzyzcjy** [comment]
A simple question: Is the lifetime correct? When looking at source code, I see

```
	fn data_bytes_mut(&mut self) -> Result<&mut [u8]> {
		match_is_continuous(self)
			.and_then(|_| {
				Ok(unsafe { slice::from_raw_parts_mut(self.data_mut(), self.total()? * self.elem_size()?) })
			})
	}

	fn data_mut(&mut self) -> &mut u8 {
		unsafe { sys::cv_Mat_getPropData(self.as_raw_mut_Mat()) }.into_result().and_then(|x| unsafe { x.as_mut() }.ok_or_else(|| Error::new(core::StsNullPtr, "Function returned Null pointer".to_string()))).expect("Infallible function failed: data_mut")
	}

	fn as_raw_mut_Mat(&mut self) -> *mut c_void;
```

no explicit lifetime spcifiers. I am a bit worried whether Rust will always guess the correct lifetime?

In other words, since you are manipulating the raw pointers directly, is it possible that, the Mat itself is dropped, but the `&mut [u8]` underlying bytes are still there?

Thanks!

**Comment by twistedfall** [comment]
> is it possible that, the Mat itself is dropped, but the &mut [u8] underlying bytes are still there?

Nope, in this case lifetime elision rules apply, so it's like the function signature was `fn data_bytes_mut<'a>(&'a mut self) -> Result<&'a mut [u8]>`. But in general because the OpenCV API surface is very large and mostly automatically translated into Rust there are cases where the functions are not sound. E.g. `Mat::roi` will happily give you a (hidden) mutable reference to a `&Mat`.

**Comment by fzyzcjy** [comment]
> Nope, in this case lifetime elision rules apply, so it's like the function signature was fn data_bytes_mut<'a>(&'a mut self) -> Result<&'a mut [u8]>. 

Sounds reasonable, thanks!

Shall we make it a bit explicit, since lifetime is quite important, especially for those raw pointers which Rust will not help that much?

> But in general because the OpenCV API surface is very large and mostly automatically translated into Rust there are cases where the functions are not sound. E.g. Mat::roi will happily give you a (hidden) mutable reference to a &Mat.

Oops... So what should we do? IMHO Rust said that it uses the immutability for heavy optimizations (seems even for aliasing). So if we tell Rust it is immutable but it is indeed mutable, will we get into trouble?

**Comment by twistedfall** [comment]
> Shall we make it a bit explicit

I don't think it's necessary, the lifetime omission due to elision rules is ubiquitous in the Rust programs and their knowledge is often implied.

> So if we tell Rust it is immutable but it is indeed mutable, will we get into trouble?

In this case unlikely, because the actual Mat is behind the mutable pointer and all accesses to it are behind FFI, so I don't really expect any optimization to apply there.

**Comment by fzyzcjy** [comment]
Sounds reasonable. Thanks!
