### ISSUE TITLE
opencv::highgui::imdecode is missing

### ISSUE THREAD

**Issue by eHammarstrom** [twistedfall/opencv-rust#28]
I am handling images in memory and would like to decode a buffer into an opencv::core::Mat struct, however this is not possible as opencv::highgui::imdecode is missing.

The function in question can be found [here](http://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#imdecode).

The current workaround would be to write buffer to an image file and then load via opencv::highgui::imread, this is painful just to type :)

**Comment by initiumSrc** [comment]
I just noticed the function has not been renamed when looking in the [gen_rust.py](https://github.com/kali/opencv-rust/blob/master/gen_rust.py#L163).

`"cv_imdecode_InputArray_buf_int_flags": "-",`

However I am unable to rename the function and build the project due to several undefined references, the build output can be found [here](https://gist.github.com/initiumSrc/d2d77dbcc7017c31264b876cfdf33160).

**Comment by twistedfall** [comment]
Please check the latest master if you're still interested, imdecode is there, it's built against opencv-3.4.5 though
