### ISSUE TITLE
&Vector iterator strange behavior, T instead of &T

### ISSUE THREAD

**Issue by Machine-Jonte** [twistedfall/opencv-rust#331]
When iterating over &Vector, it behaves strangely. It does not move, yet return type T. More logically it would return &T.

```rust
// Iterating with std Vec
pub fn take_keypoints(
    kp1: &cv::core::Vector<cv::core::KeyPoint>,
    kp2: &cv::core::Vector<cv::core::KeyPoint>,
    matches: &Vec<cv::core::DMatch>,
) {
    matches.into_iter().map(|a: &DMatch | ... )
}

// Iterating with cv::core::Vector
pub fn take_keypoints(
    kp1: &cv::core::Vector<cv::core::KeyPoint>,
    kp2: &cv::core::Vector<cv::core::KeyPoint>,
    matches: &Vector<cv::core::DMatch>,
) {
    matches.into_iter().map(|a: DMatch | ... )
}

```

**Comment by twistedfall** [comment]
The reasoning behind this is that it's not really possible in a general case to return a reference to the internal element in the Vector because it's stored on the C++ side. So when an element gets through the FFI boundary we have just `DMatch` in the function scope on the Rust side: https://github.com/twistedfall/opencv-rust/blob/147c80464c12a05a7b095485cbf5a151b19ccc51/src/manual/core/vector/iter.rs#L77 so it's only possible to return owned element, there is no place to create a reference to.
