### ISSUE TITLE
Display Video frame correctly from a stream source

### ISSUE THREAD

**Issue by JoyBoy-369** [twistedfall/opencv-rust#398]
Hi @twistedfall ,

I would like to display video frames from the data I'm receiving via an NDI(Newtek) source. The video frames are streamed continuously from said source. I am able to display it on the screen however it seems I'm doing something wrong. 
The left picture is whatI'm getting and the right one is the correct output.

<img width="181" alt="Screenshot 2022-12-08 at 4 08 25 PM" src="https://user-images.githubusercontent.com/14374646/206425847-620cb95e-970a-48a0-84c5-07f07750f1b5.png"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img width="265" alt="Screenshot 2022-12-08 at 4 08 13 PM" src="https://user-images.githubusercontent.com/14374646/206425860-5e41070f-b97c-4507-ac05-59d71e878e2d.png">

The code I tried ( I'm new to rust and opencv, please correct me if I'm doing things wrong):

`data` is the video frame data as bytes `[u8]`
`video.width` and `video.height` are 1920 X 1080

Other information about the video frame :
```
CCtype: UYVY
frame format type:  Progressive 
frame_rate_d: 1  
frame_rate_n: 30 
```

```
 let video_frames = Mat::from_slice(&data).unwrap(); 
 let video_frames = video_frames.reshape_nd(4, &[video.height, video.width]).unwrap();
 highgui::imshow("window", &video_frames)?;
```

Also, if I have to resize the video output to say 512 X 256 on the window do I have to use `resize` function?

**Comment by twistedfall** [comment]
That sounds like your problem is with the OpenCV usage, not specifically with its Rust bindings. Just from the looks of it seems like you're interpreting the color order wrong, e.g. your `data` is RGB, but OpenCV internally expects to work with BGR. You might try [`imdecode`](https://docs.rs/opencv/latest/opencv/imgcodecs/fn.imdecode.html) if your frame is an actual encoded image in a format that OpenCV understands.

It's also strange that left image contains more information than the right one, from your description that doesn't seem like it should be a case.

For resizing, yes, [`imgproc::resize`](https://docs.rs/opencv/latest/opencv/imgproc/fn.resize.html) is the function you're looking for.

Generally I might be able to help more if you have a corresponding C++/Python code that works for you. I will then help you translate that to Rust.

**Comment by JoyBoy-369** [comment]
Many thanks @twistedfall. It indeed was the colour format. The video frame format is uyvy and I had to convert it to BGR as you suggested.  
Also, the right image went out of the screen so I couldn't capture all of it with the snip tool.
Below is the code that worked for me : 

```
// data is the video frame data as bytes [u8]
let data_ptr: *mut c_void = data.as_ptr() as *mut c_void;
let video_frame = unsafe {
     Mat::new_rows_cols_with_data(video.height, video.width, CV_8UC2, data_ptr, Mat_AUTO_STEP)?
};
let mut frame = Mat::default();
imgproc::cvt_color(&video_frame, &mut frame, COLOR_YUV2BGR_UYVY, 0)?;
```
