### ISSUE TITLE
[Build Error] Cannot initialize clang ,libclang.dll could not be opened

### ISSUE THREAD

**Issue by zixun** [twistedfall/opencv-rust#449]
1. Operating system : Windows 11
2. choco install llvm opencv  and current set the enviroment variables
3. OpenCV version: 4.6.0
4. rustc version (`rustc --version`): rustc 1.68.2 (9eb3afe9e 2023-03-27)
5. Attach the full output of the following command from your project directory:
   ```shell script
   RUST_BACKTRACE=full cargo build -vv 
   ```

**Comment by zixun** [comment]
cargo build -vv log is too long,so i add it to : https://gist.github.com/zixun/a7f320f943ac396e2100

**Comment by zixun** [comment]
maybe same to this issues :https://github.com/twistedfall/opencv-rust/issues/388

**Comment by twistedfall** [comment]
This problem is not specifically caused by the `opencv` crate, but by the `clang`, for some reason it can't load the library. It doesn't provide too much detail about it, but you can check [google](https://www.google.com/search?q=%22could+not+be+opened%3A+LoadLibraryExW+failed%22) and the [CI script](https://github.com/twistedfall/opencv-rust/blob/master/ci/script.sh#L6), especially the line where it sets the path to clang:
```
export LIBCLANG_PATH="/C/Program Files/LLVM/bin"
```

**Comment by twistedfall** [comment]
Please feel free to reopen this issue if you still can't get it working
