### ISSUE TITLE
Ability to disable rerun

### ISSUE THREAD

**Issue by guskovd** [twistedfall/opencv-rust#535]
It seems to me that rerun for the opencv crate works too often. Rebuild takes a lot of time
Therefore, I would like to be able to disable the call to https://github.com/twistedfall/opencv-rust/blob/2cb0af9eadc0b38a1c154e9d5538748baea06a6a/build.rs#L391, for example, using an environment variable.
This way, I can take all the risks of an incorrect rebuild on myself and, if something happens, just call `cargo clean`

**Comment by twistedfall** [comment]
To be honest such a hack doesn't feel right with me. Maybe it's a good idea to investigate what's triggering those rebuilds and fix this? Either on the crate side or in your setup. Additionally to speed up rebuilds you can try only including the OpenCV modules that you're using by specifying something like:
```
opencv = { version = "0.88", default-features = false, features = ["calib3d", "features2d", "flann"]}
```

**Comment by twistedfall** [comment]
I hope that the issue you were having is not happening anymore!

**Comment by delins** [comment]
I had an issue that sounds similar to this. On a Windows machine, [cargo::rerun-if-env-changed](https://github.com/twistedfall/opencv-rust/blob/76c421f1be6e49119f5cfb817917035bbc115309/build.rs#L231) for `VCPKG_ROOT` triggered the rebuild even when it wasn't necessary. I verified this by removing `VCPKG_ROOT` from `AFFECTING_ENV_VARS` and cleaning the opencv-rust crate's build cache so that the change got picked up.

The solution was to not set the environment variable in powershell (`$env:VCPKG_ROOT="..."`), but in `.cargo/config.toml` instead (I set it in the global config):
```rust
[env]  
VCPKG_ROOT = "..."
```

This might mean that an env variable in powershell isn't seen in every step of the cargo build/doc process, making cargo think it changed from nothing to something or vice versa, and therefore flagging the opencv-rust cache as dirty. I don't know why.
