### ISSUE TITLE
Expose `aruco` module

### ISSUE THREAD

**Issue by RealOrangeOne** [twistedfall/opencv-rust#54]
My the looks of the library, `aruco` isn't available, and is explicitly ignored in `build.rs`. Is there a reason for this?

What would be required to expose the `aruco` OpenCV module? 

I'm definitely happy to help test this!

**Comment by twistedfall** [comment]
Generally modules (and header files) are disabled because they contain some feature that causes build to fail and there isn't an quick and obvious fix. So the initial approach to enabling them would be to just remove the line from `ignore_modules` and try to build the crate. Chances are that it's successful even without additional fixes. If it still fails, then generation scripts will need to be adjusted to accommodate some specific feature of the module. I'll try to look into it as time permits.

**Comment by RealOrangeOne** [comment]
I might have some time in the short term to look into these build errors, see what they are.

Not sure whether I have the knowledge to fix them, but I should be able to point you in the right direction!

**Comment by twistedfall** [comment]
Version 0.21.1 contains support for aruco module. Please do test and share the feedback.
