### ISSUE TITLE
Need help: How to build a CV::Mat from Vec<u8> of BGR24?

### ISSUE THREAD

**Issue by tubzby** [twistedfall/opencv-rust#585]
I want to create a cv::Mat from a `Vec<u8>` which is in BGR24 format, I tried the following:

```rust

let mat= Mat::new_rows_cols_with_data(
    1920,
    1080,
    &rgb_data,
)?;

```

But it failed with error: The length of the slice: 6220800 must match the passed row: 1920 and column: 1080 counts exactly (code: StsUnmatchedSizes, -209).

It seems that `new_rows_cols_with_data` only supports `Vec<u32>`, is that the case? do I need to make a `Vec<u32>` manually?

**Comment by twistedfall** [comment]
One of the ways to do that without copying the data is with a bit of unsafe:
```rust
let mat = unsafe { Mat::new_rows_cols_with_data_unsafe_def(1920, 1080, Vec3b::opencv_type(), rgb_data.as_mut_ptr().cast()) }?;
```
And you must make sure that you drop `mat` before `rgb_data` so that it doesn't reference the freed data.

But your use case is completely valid, I will add ability to build such `Mat`s without copying the data from byte arrays in the next release, thanks for the report!

**Comment by tubzby** [comment]
Thank you!
Another question: Is there a way to update an existing `Mat` with `Vec<u8>`？

**Comment by twistedfall** [comment]
You can do something like this:
```rust
mat.data_bytes_mut()?.copy_from_slice(&bytes);
```

**Comment by tubzby** [comment]
Very helpful!
