### ISSUE TITLE
Why is it so terribly hard to build this?

### ISSUE THREAD

**Issue by CodecNomad** [twistedfall/opencv-rust#590]
Every other crate is cargo add xyz and you're ready to go.

**Comment by twistedfall** [comment]
Because this crate is just Rust-friendly bindings to the C++ OpenCV library, so it requires that OpenCV itself is present in your system before you can use the crate.

Furthermore OpenCV itself is highly configurable with multiple modules that can be switched on and off based on the available dependencies and build configuration so there is no way to provide a pre-generated one-fits-all set of bindings. And thus the crate must find the installed OpenCV and then based on the particular configuration of the installed library generate a set of bindings tailored to its particular configuration.

To generate the bindings you need to analyze C++ headers that come with the installed OpenCV and that's why the crate uses another system library `libclang` (a part of llvm/clang) that allows to analyze C++ code from Rust.

**Comment by CodecNomad** [comment]
Oh, I see. Thanks
