### ISSUE TITLE
Consider removing unnecessary result return

### ISSUE THREAD

**Issue by jerry73204** [twistedfall/opencv-rust#73]
I noticed bunch of trivial methods have result return types that are barely due to ffi or barely end in error. For example, the [Mat::size](https://github.com/twistedfall/opencv-rust/blob/98153aa337e15cd2b22fe0430307f1e0f5b41013/src/manual/core/mat.rs#L385), Mat::rows and Mat::cols. I think it can simply panic if it's due to implementation error.

In my opinion, we can look at [tch::Tensor](https://docs.rs/tch/0.1.1/tch/struct.Tensor.html)'s approach. It's a crate that ports libtorch to rust. It generates a series of methods named  `f_METHOD()`, indicating a fallible method, along with `METHOD()` that wraps around the former. For example, `add()` always return the value of `f_add()` and panics if `f_add()` fails.

EDIT:
Plus that we can add a fallible `f_clone()` and implement `Clone` trait for `Mat`. I would give us some convenience in the case that I can derive `Clone` on struct with a `Mat` field.

**Comment by twistedfall** [comment]
That's a nice idea. But I feel that we should limit it to some specific simple methods, inflating the whole API with those mirror panicking methods would be too much. Do you maybe have an idea of which methods merit having a panicking version besides those you already mentioned?

**Comment by jerry73204** [comment]
Find those methods on OpenCV reference without error returns. Once the C++ side promises non-failure return, the Rust side should work accordingly. Otherwise, panic at linking or implementation error.

Based on this rule, the comprehensive non-failure methods for `Mat` would be `at`, `col`, `clone`, `copySize`, `create`, `cross`, `empty`, etc. Maybe we can follow tch's way to have separate mod for `f_*` methods.

**Comment by twistedfall** [comment]
Some progress on that is done in v0.30.0. Property setters and getters + those functions marked as CV_NOEXCEPT (very few in total) now return value directly instead of `Result`. Please note that this version comes with the totally rewritten binding generator and you will need llvm installed instead of python to be able to correctly regenerate bindings. Please see the [changelog](https://github.com/twistedfall/opencv-rust/blob/master/CHANGES.md) and [readme](https://github.com/twistedfall/opencv-rust/blob/master/README.md) for more details.
