### ISSUE TITLE
Enable "text" module

### ISSUE THREAD

**Issue by TheRadioGuy** [twistedfall/opencv-rust#77]
Can I detect text with that thing?

**Comment by twistedfall** [comment]
Generally you can do anything that OpenCV can. There are some limitations like missing functions and some non-core modules that are not exported at all. If you need some OpenCV function and you see that it's missing in the bindings please report that and I will see what can be done.

**Comment by TheRadioGuy** [comment]
I guess OpenCV’s EAST text detector is missing

**Comment by twistedfall** [comment]
Can you give me the link to the documentation or the name of the specific class/function?

**Comment by TheRadioGuy** [comment]
https://docs.opencv.org/master/d4/d61/group__text.html

**Comment by twistedfall** [comment]
Yep, this module is currently excluded from the generation. I'll see if it's easy to enable it.

**Comment by twistedfall** [comment]
Fixed in v0.30.0. Please note that this version comes with the totally rewritten binding generator and you will need llvm installed instead of python to be able to correctly regenerate bindings. Please see the [changelog](https://github.com/twistedfall/opencv-rust/blob/master/CHANGES.md) and [readme](https://github.com/twistedfall/opencv-rust/blob/master/README.md) for more details.

**Comment by TheRadioGuy** [comment]
Got it, thanks!
