### ISSUE TITLE
build script deletes DLLs added by vcpkg to OUT_DIR

### ISSUE THREAD

**Issue by mcgoo** [twistedfall/opencv-rust#97]
The build script deletes everything in OUT_DIR. The vcpkg helper copies all of the DLLs required by the application into OUT_DIR which allows `cargo run` etc to be able to start the app without adjusting the path. (I tested and for me it works if the DLLs do not get deleted.) If you'd like to change the existing behavior, `cargo run` works if the cleanup deletes everything but DLLs. It might be better to just to make the glob more specific about what to delete. If you'd like that changed I can do it - let me know if you want to only leave the DLLs, or what specific files you'd like to delete. 

https://github.com/twistedfall/opencv-rust/blob/7e13d0ccf55a58655abb30cc3a267dea597a746c/build.rs#L549-L553

**Comment by twistedfall** [comment]
Oh, I see. Well, the source of the problem here is that vcpkg does its job before we call `build_wrapper`. I'll need to check if it's possible to fix that. In the meantime I'm more than happy to accept a workaround PR. Either way (removing everything but dlls or removing only specific files) is fine.

**Comment by mcgoo** [comment]
Not that I'm recommending you do it this way, but if you need to you can call vcpkg more than once, and on the early pass use it's config flags in order to not emit metadata and copy the dlls around.
